services:
    postgres:
        image: postgres:17-alpine
        container_name: delivery-db
        env_file:
            - ./.env
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - pg-cocobambu-delivery:/var/lib/postgresql/data

volumes:
    pg-cocobambu-delivery:
        driver: local
